name: "AWS Stack Outputs to Env"
description: |
  Collect variables from specified stack outputs and export them to env vars

branding:
  icon: "settings"
  color: "orange"

inputs:
  access_key_id:
    description: "AWS Access Key ID"
    required: true
  secret_access_key:
    description: "AWS Secret Access Key"
    required: true
  region:
    description: "AWS Region"
    required: true
  stack_name:
    description: "Cloudformation Stack Name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get Stack Outputs
      id: get_stack_outputs
      shell: bash
      run: |
        echo "Collecting stack outputs from AWS Cloudformation"
        aws cloudformation describe-stacks --stack-name "${{ inputs.stack_name }}" --query 'Stacks[0].Outputs' --output json \
        | jq -r 'keys[] as $k | "\($k)=\(.[$k].OutputValue)"') \
        | while read line ; do mask=$(cut -d "=" -f2- <<< $line) && echo "::add-mask::${mask}" && echo $line >> $GITHUB_ENV ; done
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.secret_access_key }}
        AWS_DEFAULT_REGION: ${{ inputs.region }}
